### ISSUE TITLE
re-run npm install FAILS

### ISSUE THREAD

**Issue by tiago-pullup** [Polarisation/indexeddb-export-import#14]
if this module is already installed in the project, running the **npm insatll** fails with the message

`npm install
npm ERR! code EISGIT
npm ERR! path **\node_modules\indexeddb-export-import
npm ERR! git **\node_modules\indexeddb-export-import: Appears to be a git 
repo or submodule.
npm ERR! git     **\node_modules\indexeddb-export-import
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     **\AppData\Roaming\npm-cache\_logs\2020-06-01T13_10_57_546Z-debug.log`

This error is caused because **tar.gz** in version 2.0.2 has a directory **. git ** inside, the solution is to remove and resend. The package **. zip ** is OK

**Comment by tiago-pullup** [comment]
by the way thank you very much for the excellent module

**Comment by Polarisation** [comment]
Thanks for reporting this. Just released v2.0.3 to fix this.
