### ISSUE TITLE
Looking for suggestion around how to use in browser execution js

### ISSUE THREAD

**Issue by sombhattacharyya1983** [Polarisation/indexeddb-export-import#17]
I have a requirement to take a backup of indexed database from the browser.  Can you please point me to a place that explains this or give me some pointers of how to use this library to run the backup from a browser.

**Comment by Polarisation** [comment]
Are you backing up an IndexedDB for a website you develop? You could write some code to export this data in the IndexedDB using this module. This module will only pull the data out of IndexedDB, it doesn't provide any UI - you'd need to write that.

**Comment by sombhattacharyya1983** [comment]
Yes so we have a site that saves some stuff to the indexed database. I need to dump data to  debug issues. I am not looking for a fancy ui. Maybe a simple index.html that executes this and saves to file. The page would open on a tablet with no node.js installed. So i am looking for a simple browser based solution.

**Comment by Polarisation** [comment]
You can use this in the browser. It will help you get the data out of IndexedDB, but you'd have to write the code to save it to a file.

If you need support for older browsers you will need to use a transpiler like babel.

**Comment by sombhattacharyya1983** [comment]
Thanks.

**Comment by mymirai-nikki** [comment]
> Are you backing up an IndexedDB for a website you develop?

can I use this for backing up on a website that I don't develop?

**Comment by mymirai-nikki** [comment]
I look at the source code, but I didn't see any call to `createObjectStore`, is this project only export and import the data stored in already existed object store?

**Comment by Polarisation** [comment]
> I look at the source code, but I didn't see any call to createObjectStore, is this project only export and import the data stored in already existed object store?

Yes.

> can I use this for backing up on a website that I don't develop?

It is not designed for that but the functions in this codebase are quite simple and self-contained, you could probably copy & paste them into the browser console to use them there.
