### ISSUE TITLE
Hi, is this possible to use this project to backup data inside indexedDB in Electron APP?

### ISSUE THREAD

**Issue by hz0324** [Polarisation/indexeddb-export-import#2]
We are trying to converting our Web App into an Electron APP.
We use DexieJS in our Web App, so we prefer to use it as well in our Electron APP.

However, we are worried about the data safety, since there are maybe some scenarios, the data inside indexedDB MIGHT be deleted. Such as reinstall the App, auto update the App etc. We are not sure about it. But we can not risk it.

I found this project while searching around the internet. I am wondering maybe this could be used to backup the indexedDB.

Is this possible? 
Thanks.

**Comment by dodgy99** [comment]
I would also be interested in whether this is possible and perhaps some instructions on how it could be done. Thanks

**Comment by Polarisation** [comment]
Sorry for the delayed reply. It could be used to back up the content of IndexedDB, yes. I originally developed this for use in an Electron app to save a copy of an IndexedDB database. In that case I used a save dialog but it could be done automatically in the background too. This module will only help with get the data into JSON format - you will have to write code to save to a file separately.
